### ISSUE TITLE
如何直接定位到某条

### ISSUE THREAD

**Issue by i2863CookieZJ** [TokenYc/DouyinVideoList#1]
列表有10条  如何直接定位到第5条

**Comment by i2863CookieZJ** [comment]
建议播放器设置成单例

**Comment by TokenYc** [comment]
re1:先调用recyclerView或者layoutManager的scrollToPosition方法,然后调用播放方法就好了。
re2:确实用单例模式会好些，有空会实现下。
@i2863CookieZJ

**Comment by i2863CookieZJ** [comment]
@TokenYc  我尝试了scrollToPosition 发现都是无效的  但是smoothScrollToPosition却是可以的  这是可能是什么原因

**Comment by i2863CookieZJ** [comment]
@TokenYc scollToPosition无效的原因找到了，不能在onInitComplete设置，但是adjustVideoSize中没有处理旋转信息
